[package]
name = "rustchain"
version = "0.1.0"
authors = ["talentedev <cryptoveteran24@gmail.com>"]

[dependencies]
time = "0.1"
sha1 = { version = "0.6.0", features = ["std"] }
bincode = "1.0.0"
serde = "*"
serde_derive = "*"
